<a href="https://colab.research.google.com/github/Alisherbakh/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
print(pd.__version__)

2.2.3

In [ ]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Lambo"],
  'counts': [3, 7, 2, 4, 5, 6]
}

print(mydataset)
print("=======")

df = pd.DataFrame(mydataset)
print(df)

{'cars': ['BMW', 'Volvo', 'Ford', 'Tesla', 'Ferrari', 'Lambo'], 'counts': [3, 7, 2, 4, 5, 6]}
=======
      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       4
4  Ferrari       5
5    Lambo       6

In [ ]:
df.head() # default 5 rows korsatadi, raqam qoyilsa raqamga qarab, - bilan raqam kiritilsa oxiridan korsatadi

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       4
4  Ferrari       5

In [ ]:
df.tail() # default 5 rows, oxiridan korsatadi, head ni teskarisi

      cars  counts
1    Volvo       7
2     Ford       2
3    Tesla       4
4  Ferrari       5
5    Lambo       6

In [ ]:
df.shape #property bu dataset ni shape ni aniqlaydi (6 qator, 2 ustun)

(6, 2)

In [ ]:
df.columns # dataframe columns and type ni korsatadi

Index(['cars', 'counts'], dtype='object')

In [ ]:
df.dtypes # data larnni type ni korish uchun

cars      object
counts     int64
dtype: object

In [ ]:
df.describe() # numerical columns only(faqat raqamlar), statistic describe qiladi,
#include="all" argument berilsa(hamma columns ni describe qil degani, faqat raqamlardan tashqarisini ham)
#std raqamlar qanchalik bir biriga oxshash, 0 bolsa bir xil boladi

         counts
count  6.000000
mean   4.500000
std    1.870829
min    2.000000
25%    3.250000
50%    4.500000
75%    5.750000
max    7.000000

In [ ]:
df.iloc[0] # argument numberga qarab osha row dagi malumotni chiqarib beradi, - bilan raqam yozilsa oxiridan keladi
# [1:4] bolsa 1,2,3 row dagi malumotlarni olib keladi
# [2:] 2- row dan bolshalab hamma malumotlarni olib keladi

cars      BMW
counts      3
Name: 0, dtype: object

In [ ]:
df.loc[:,"cars"] # value kutadi, 1- si qatorni(: hammasi degani),
#2- columns name(ex: cars, yoki counts)
# ham row dan, ham column(label) name dan foydalanib malumotlarni korish imkonini beradi

0        BMW
1      Volvo
2       Ford
3      Tesla
4    Ferrari
5      Lambo
Name: cars, dtype: object

In [ ]:
df["counts"] > 3 # misol 3 dan yuqori mashinalarni qaytar desak(konditionlardan foydalanib)
# boolen qaytaradi
# df[df["counts"] > 3] data frame ga orab olsak, ma'lumotlarni ham korsatadi
# df[df["cars"] == "BMW"] bmw ga teng larni olib kelib beradi( filtering)

0    False
1     True
2    False
3     True
4     True
5     True
Name: counts, dtype: bool

In [ ]:
df.mean(numeric_only=True) #faqat raqamlardan tashkil topgan column valuesini ortachasini korsatib beradi(mean value)
# numeric_only=True = faqat raqamlar dan iborat degani
# df["counts"].mean() = faqat counts column ni ortachasini olib ber dgani

counts    4.5
dtype: float64

In [ ]:
df.sum() #har bitta column ni umumiy yigindisini chiqarib beradi

cars      BMWVolvoFordTeslaFerrariLambo
counts                               27
dtype: object

In [ ]:
df.min() # minimum malumotni ni chiqarib beradi

cars      BMW
counts      2
dtype: object

In [ ]:
df.max() # maximumni chiqarib beradi

cars      Volvo
counts        7
dtype: object

In [ ]:
df.median(numeric_only=True) # middle value ni olib beradi

counts    4.5
dtype: float64

In [ ]:
df.count() # malumotlani oqib chiqadi va null value larni qidiradi
# hozr 6 malumot bor va hammasi ni value si bor

cars      6
counts    6
dtype: int64

In [ ]:
df.std(numeric_only=True) #har bir raqamli ustunning standart og’ishini (standard deviation) hisoblaydi.

counts    1.870829
dtype: float64

In [ ]:
# data larni clean ing qilish da(tozalash da ishlatiladi)
data_with_missing ={
    "cars": ["BMW", None, "Ford", "Tesla", None, "Lambo", "GM", None],
    "counts": [None, 7, 2, 4, 9, None, 2, None]
}

df_missing =  pd.DataFrame(data_with_missing)
print(df_missing)

    cars  counts
0    BMW     NaN
1   None     7.0
2   Ford     2.0
3  Tesla     4.0
4   None     9.0
5  Lambo     NaN
6     GM     2.0
7   None     NaN

In [ ]:
df_missing.isnull() # data larni clean ing qilish da(tozalash da ishlatiladi)
# boolen da True(data yoq bolsa)/False(data bor bolsa) da chiqarib beradi
# df_missing.isnull().sum() ni ham qoshadigan bolsak, data yoq row larni soni ni chiqaradi

    cars  counts
0  False    True
1   True   False
2  False   False
3  False   False
4   True   False
5  False    True
6  False   False
7   True    True

In [ ]:
df_missing.dropna() # malumotlarni ochirish uchun
# data si yoq qatorni ochirib tashlaydi, data si toliqlarni chiqarib beradi
# df_missing.dropna(how="all") toliq missing value bor qatorni faqat ochiradi

    cars  counts
2   Ford     2.0
3  Tesla     4.0
6     GM     2.0

In [ ]:
df_missing.dropna(axis=1) #malumoti yoq hamma column larni tashlab yuboradi,
#faqat column boyicha tekshiradi
# df_missing.dropna(axis=1) qaysi clumn da 1 ta data bolmasa ham ochirib tashlaydi
# df_missing.dropna(subset=['counts']) faqat counts column ni tekshirib beradi

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7]

In [ ]:
df_missing.fillna(7) # value si yoq qatorlarga malumot qoyib qoyadi
# missing value lar ga argument da berilgan qiymatni  qoyib chiqadi
# df_missing.fillna("unknown") string bolishi ham m-
# df_missing.fillna("cars": "unknown", "counts": 0)  column lardan kelib chiqib value kiritishimiz mumkun

    cars  counts
0    BMW     7.0
1      7     7.0
2   Ford     2.0
3  Tesla     4.0
4      7     9.0
5  Lambo     7.0
6     GM     2.0
7      7     7.0

In [ ]:
df = pd.read_csv("Titanic-Dataset.csv") # file ni oqib beradi

df.head()

#df = pd.read_excel("Titanic-Dataset.xlsx")
#df = pd.read_json("Titanic-Dataset.json")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.to_excel("output.xlsx")#file ni export qilib olish uchun

In [ ]:
# Series => 1D lar bilan ishlashda qulay
cars = pd.Series(["BMW", "Tesla", "Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [ ]:
cars_series = data_with_missing["cars"]
print(cars_series)

['BMW', None, 'Ford', 'Tesla', None, 'Lambo', 'GM', None]